### PR TITLE
Add links to the readme

### PR DESCRIPTION
**Pull request by SarahAlidoost**
The section **Course material** will be used during the course.

### CODE REVIEW

**Review by bouweandela — CHANGES_REQUESTED** [review]
Thanks @SarahAlidoost! Just one small comment, could you remove  'model-' from the sentence 'the model-specific analysis called diagnostic script' in the presentation? The idea behind diagnostic scripts is that they can be applied to data from any model (provided it follows the CMOR/CF Conventions), so they are not model specific.

**Review by Peter9192 — APPROVED** [review]
The slides look good. Just realized that one thing that is perhaps missing is the distinction between the CLI, and the Python API that we'll be using during the course. Will you explain that in the introduction?

**Comment by SarahAlidoost** [comment]
> Thanks @SarahAlidoost! Just one small comment, could you remove 'model-' from the sentence 'the model-specific analysis called diagnostic script' in the presentation? The idea behind diagnostic scripts is that they can be applied to data from any model (provided it follows the CMOR/CF Conventions), so they are not model specific.

right, it is removed.

**Comment by SarahAlidoost** [comment]
> The slides look good. Just realized that one thing that is perhaps missing is the distinction between the CLI, and the Python API that we'll be using during the course. Will you explain that in the introduction?

yes, the idea is to explain it during the presentation. However, I revised the slides too, See slide number 10.

**Review by bouweandela — APPROVED** [review]

**Pull request merged**
